import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, Mate_SC } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ['latin'] })
const mateSC = Mate_SC({ 
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-mate-sc'
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
  
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} ${mateSC.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
